### ISSUE TITLE
实现v1.5版本已经实现的功能

### ISSUE THREAD

**Issue by fzdwx** [fzdwx/burst#30]
当前golang的版本基本已经写完了，接下来就是完成以前实现的功能了。

- [x] 动态关闭代理端口
- [ ] HTTP代理统一监听一个端口(自定义域名)
- [ ] 一些监控指标(有什么需要监控的数据，各位可以提一下建议。)

**Comment by D06F6E67** [comment]
可以搞个可视化界面

**Comment by fzdwx** [comment]
> 可以搞个可视化界面
@LiJiaDong0922 

---
写个cli还可以做到，我前端属实拉 😄

**Comment by fzdwx** [comment]
HTTP代理统一监听一个端口(自定义域名)

问题：
> 是基于`net.http`还是直接使用`net.tcp`？

todo

**Comment by whatwewant** [comment]
可视化我可以帮忙提供支持 @fzdwx

**Comment by gaoqiao147** [comment]
你好，请问api调用具体端口号是什么呀？在服务端调用还是客户端调用？

**Comment by fzdwx** [comment]
https://github.com/fzdwx/burst/blob/main/cmd/server/server.yaml

高桥凉介 ***@***.***> 于2023年5月19日周五 21:24写道：
